# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}: {
  imports =
    [
      (modulesPath + "/profiles/qemu-guest.nix")
    ]
    ++ [./disko.nix]
    ++ [./headscale.nix];

  boot.initrd.availableKernelModules = ["ata_piix" "uhci_hcd" "virtio_pci" "sr_mod" "virtio_blk"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    efiInstallAsRemovable = true;
    devices = ["/dev/vda"];
  };

  networking = {
    useDHCP = false;
    interfaces.ens18 = {
      useDHCP = false;
      ipv4.addresses = [
        {
          address = "185.203.117.165";
          prefixLength = 24;
        }
      ];
      ipv6.addresses = [
        {
          address = "2a07:5741:0:842::1";
          prefixLength = 64;
        }
      ];
    };
    defaultGateway = "185.203.117.1";
    defaultGateway6 = {
      address = "fe80::1";
      interface = "ens18";
    };
    nameservers = ["8.8.8.8" "1.1.1.1"];
  };

  services.openssh.enable = true;

  users.users.root.openssh.authorizedKeys.keys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIP1hoZGyBJs13/TJSFYBemhMtaY6Qy78xTjV4Wp2QMQ9 ezozbek@swift"
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILvEU2QT26Kbj0Kyi3JwXU3VRGrLbQbQLC32FXqkwmxF ezozbek@nixos"
  ];

  services._3proxy = {
    enable = true;
    usersFile = "/etc/3proxy.passwd";
    services = [
      {
        type = "socks";
        bindPort = 1080;
        auth = ["strong"];
        acl = [
          {
            rule = "allow";
            users = ["ezozbek"];
          }
        ];
      }
    ];
  };

  networking.firewall.allowedTCPPorts = [1080];

  environment.etc = {
    "3proxy.passwd".text = ''
      ezozbek:CR:$1$2JbeTWNL$WXwQ3H/ykbzG3UagFikLA1
    '';
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  system.stateVersion = "23.06";
}
